name: sesori_client_workspace
publish_to: none

environment:
  sdk: ^3.12.2
  flutter: ">=3.44.6 <3.45.0"

workspace:
  - app
  - module_core
  - module_auth
  - module_prego
  - module_desktop_core
  - desktop
