// GENERATED FILE - DO NOT EDIT BY HAND
// Source: anomalyco/opencode@v1.16.2 (76c631d198f9ff620e15468e45f3457d50481b57)
// Generated: 2026-06-08T14:24:06.206900Z

import 'package:meta/meta.dart';
import 'event.tui.command.execute.dart';
import 'event.tui.prompt.append.dart';
import 'event.tui.session.select.dart';
import 'event.tui.toast.show.dart';
import 'event_account_added.dart';
import 'event_account_removed.dart';
import 'event_account_switched.dart';
import 'event_catalog_model_updated.dart';
import 'event_command_executed.dart';
import 'event_file_edited.dart';
import 'event_file_watcher_updated.dart';
import 'event_global_disposed.dart';
import 'event_installation_update_available.dart';
import 'event_installation_updated.dart';
import 'event_lsp_updated.dart';
import 'event_mcp_browser_open_failed.dart';
import 'event_mcp_tools_changed.dart';
import 'event_message_part_delta.dart';
import 'event_message_part_removed.dart';
import 'event_message_part_updated.dart';
import 'event_message_removed.dart';
import 'event_message_updated.dart';
import 'event_models_dev_refreshed.dart';
import 'event_permission_asked.dart';
import 'event_permission_replied.dart';
import 'event_permission_v2_asked.dart';
import 'event_permission_v2_replied.dart';
import 'event_plugin_added.dart';
import 'event_project_directories_updated.dart';
import 'event_project_updated.dart';
import 'event_pty_created.dart';
import 'event_pty_deleted.dart';
import 'event_pty_exited.dart';
import 'event_pty_updated.dart';
import 'event_question_asked.dart';
import 'event_question_rejected.dart';
import 'event_question_replied.dart';
import 'event_question_v2_asked.dart';
import 'event_question_v2_rejected.dart';
import 'event_question_v2_replied.dart';
import 'event_server_connected.dart';
import 'event_server_instance_disposed.dart';
import 'event_session_compacted.dart';
import 'event_session_created.dart';
import 'event_session_deleted.dart';
import 'event_session_diff.dart';
import 'event_session_error.dart';
import 'event_session_idle.dart';
import 'event_session_next_agent_switched.dart';
import 'event_session_next_compaction_delta.dart';
import 'event_session_next_compaction_ended.dart';
import 'event_session_next_compaction_started.dart';
import 'event_session_next_context_updated.dart';
import 'event_session_next_model_switched.dart';
import 'event_session_next_moved.dart';
import 'event_session_next_prompt_admitted.dart';
import 'event_session_next_prompt_promoted.dart';
import 'event_session_next_prompted.dart';
import 'event_session_next_reasoning_delta.dart';
import 'event_session_next_reasoning_ended.dart';
import 'event_session_next_reasoning_started.dart';
import 'event_session_next_retried.dart';
import 'event_session_next_shell_ended.dart';
import 'event_session_next_shell_started.dart';
import 'event_session_next_step_ended.dart';
import 'event_session_next_step_failed.dart';
import 'event_session_next_step_started.dart';
import 'event_session_next_synthetic.dart';
import 'event_session_next_text_delta.dart';
import 'event_session_next_text_ended.dart';
import 'event_session_next_text_started.dart';
import 'event_session_next_tool_called.dart';
import 'event_session_next_tool_failed.dart';
import 'event_session_next_tool_input_delta.dart';
import 'event_session_next_tool_input_ended.dart';
import 'event_session_next_tool_input_started.dart';
import 'event_session_next_tool_progress.dart';
import 'event_session_next_tool_success.dart';
import 'event_session_status.dart';
import 'event_session_updated.dart';
import 'event_todo_updated.dart';
import 'event_vcs_branch_updated.dart';
import 'event_workspace_failed.dart';
import 'event_workspace_ready.dart';
import 'event_workspace_status.dart';
import 'event_worktree_failed.dart';
import 'event_worktree_ready.dart';

@immutable
abstract interface class Event {
  const Event();

  /// Serialize the underlying variant. Variants must override this.
  ///
  /// The return type is `Object?` (not `Map<String, dynamic>`)
  /// because some unions are string-or-object and the string
  /// variant encodes as the scalar itself, not a wrapped map.
  /// Callers pass the result straight to `jsonEncode` or
  /// another `toJson()`, both of which accept `Object?`.
  Object? toJson();

  factory Event.fromJson(Object json) {
    final map = json as Map<String, dynamic>;
    final discriminator = map["type"];
    switch (discriminator) {
      case "models-dev.refreshed":
        return EventModelsDevRefreshed.fromJson(map);
      case "plugin.added":
        return EventPluginAdded.fromJson(map);
      case "catalog.model.updated":
        return EventCatalogModelUpdated.fromJson(map);
      case "session.created":
        return EventSessionCreated.fromJson(map);
      case "session.updated":
        return EventSessionUpdated.fromJson(map);
      case "session.deleted":
        return EventSessionDeleted.fromJson(map);
      case "message.updated":
        return EventMessageUpdated.fromJson(map);
      case "message.removed":
        return EventMessageRemoved.fromJson(map);
      case "message.part.updated":
        return EventMessagePartUpdated.fromJson(map);
      case "message.part.removed":
        return EventMessagePartRemoved.fromJson(map);
      case "session.next.agent.switched":
        return EventSessionNextAgentSwitched.fromJson(map);
      case "session.next.model.switched":
        return EventSessionNextModelSwitched.fromJson(map);
      case "session.next.moved":
        return EventSessionNextMoved.fromJson(map);
      case "session.next.prompted":
        return EventSessionNextPrompted.fromJson(map);
      case "session.next.prompt.admitted":
        return EventSessionNextPromptAdmitted.fromJson(map);
      case "session.next.prompt.promoted":
        return EventSessionNextPromptPromoted.fromJson(map);
      case "session.next.context.updated":
        return EventSessionNextContextUpdated.fromJson(map);
      case "session.next.synthetic":
        return EventSessionNextSynthetic.fromJson(map);
      case "session.next.shell.started":
        return EventSessionNextShellStarted.fromJson(map);
      case "session.next.shell.ended":
        return EventSessionNextShellEnded.fromJson(map);
      case "session.next.step.started":
        return EventSessionNextStepStarted.fromJson(map);
      case "session.next.step.ended":
        return EventSessionNextStepEnded.fromJson(map);
      case "session.next.step.failed":
        return EventSessionNextStepFailed.fromJson(map);
      case "session.next.text.started":
        return EventSessionNextTextStarted.fromJson(map);
      case "session.next.text.delta":
        return EventSessionNextTextDelta.fromJson(map);
      case "session.next.text.ended":
        return EventSessionNextTextEnded.fromJson(map);
      case "session.next.reasoning.started":
        return EventSessionNextReasoningStarted.fromJson(map);
      case "session.next.reasoning.delta":
        return EventSessionNextReasoningDelta.fromJson(map);
      case "session.next.reasoning.ended":
        return EventSessionNextReasoningEnded.fromJson(map);
      case "session.next.tool.input.started":
        return EventSessionNextToolInputStarted.fromJson(map);
      case "session.next.tool.input.delta":
        return EventSessionNextToolInputDelta.fromJson(map);
      case "session.next.tool.input.ended":
        return EventSessionNextToolInputEnded.fromJson(map);
      case "session.next.tool.called":
        return EventSessionNextToolCalled.fromJson(map);
      case "session.next.tool.progress":
        return EventSessionNextToolProgress.fromJson(map);
      case "session.next.tool.success":
        return EventSessionNextToolSuccess.fromJson(map);
      case "session.next.tool.failed":
        return EventSessionNextToolFailed.fromJson(map);
      case "session.next.retried":
        return EventSessionNextRetried.fromJson(map);
      case "session.next.compaction.started":
        return EventSessionNextCompactionStarted.fromJson(map);
      case "session.next.compaction.delta":
        return EventSessionNextCompactionDelta.fromJson(map);
      case "session.next.compaction.ended":
        return EventSessionNextCompactionEnded.fromJson(map);
      case "message.part.delta":
        return EventMessagePartDelta.fromJson(map);
      case "session.diff":
        return EventSessionDiff.fromJson(map);
      case "session.error":
        return EventSessionError.fromJson(map);
      case "installation.updated":
        return EventInstallationUpdated.fromJson(map);
      case "installation.update-available":
        return EventInstallationUpdateAvailable.fromJson(map);
      case "file.edited":
        return EventFileEdited.fromJson(map);
      case "account.added":
        return EventAccountAdded.fromJson(map);
      case "account.removed":
        return EventAccountRemoved.fromJson(map);
      case "account.switched":
        return EventAccountSwitched.fromJson(map);
      case "permission.v2.asked":
        return EventPermissionV2Asked.fromJson(map);
      case "permission.v2.replied":
        return EventPermissionV2Replied.fromJson(map);
      case "file.watcher.updated":
        return EventFileWatcherUpdated.fromJson(map);
      case "pty.created":
        return EventPtyCreated.fromJson(map);
      case "pty.updated":
        return EventPtyUpdated.fromJson(map);
      case "pty.exited":
        return EventPtyExited.fromJson(map);
      case "pty.deleted":
        return EventPtyDeleted.fromJson(map);
      case "question.v2.asked":
        return EventQuestionV2Asked.fromJson(map);
      case "question.v2.replied":
        return EventQuestionV2Replied.fromJson(map);
      case "question.v2.rejected":
        return EventQuestionV2Rejected.fromJson(map);
      case "todo.updated":
        return EventTodoUpdated.fromJson(map);
      case "lsp.updated":
        return EventLspUpdated.fromJson(map);
      case "permission.asked":
        return EventPermissionAsked.fromJson(map);
      case "permission.replied":
        return EventPermissionReplied.fromJson(map);
      case "tui.prompt.append":
        return EventTuiPromptAppend1opz5ph.fromJson(map);
      case "tui.command.execute":
        return EventTuiCommandExecute0vkghdx.fromJson(map);
      case "tui.toast.show":
        return EventTuiToastShow190ap9t.fromJson(map);
      case "tui.session.select":
        return EventTuiSessionSelect16fpc99.fromJson(map);
      case "mcp.tools.changed":
        return EventMcpToolsChanged.fromJson(map);
      case "mcp.browser.open.failed":
        return EventMcpBrowserOpenFailed.fromJson(map);
      case "command.executed":
        return EventCommandExecuted.fromJson(map);
      case "project.directories.updated":
        return EventProjectDirectoriesUpdated.fromJson(map);
      case "project.updated":
        return EventProjectUpdated.fromJson(map);
      case "question.asked":
        return EventQuestionAsked.fromJson(map);
      case "question.replied":
        return EventQuestionReplied.fromJson(map);
      case "question.rejected":
        return EventQuestionRejected.fromJson(map);
      case "session.status":
        return EventSessionStatus.fromJson(map);
      case "session.idle":
        return EventSessionIdle.fromJson(map);
      case "session.compacted":
        return EventSessionCompacted.fromJson(map);
      case "vcs.branch.updated":
        return EventVcsBranchUpdated.fromJson(map);
      case "worktree.ready":
        return EventWorktreeReady.fromJson(map);
      case "worktree.failed":
        return EventWorktreeFailed.fromJson(map);
      case "workspace.ready":
        return EventWorkspaceReady.fromJson(map);
      case "workspace.failed":
        return EventWorkspaceFailed.fromJson(map);
      case "workspace.status":
        return EventWorkspaceStatus.fromJson(map);
      case "server.connected":
        return EventServerConnected.fromJson(map);
      case "global.disposed":
        return EventGlobalDisposed.fromJson(map);
      case "server.instance.disposed":
        return EventServerInstanceDisposed.fromJson(map);
      default:
        throw FormatException('Unknown Event value: $discriminator');
    }
  }
}
