targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
      freezed:
        options:
          format: false
          map: false
          when: false
      drift_dev:
        options:
          databases:
            default: lib/src/bridge/persistence/database.dart
          write_to_columns_mixins: true
