// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionWorktreesTable,
  ];
  late final Shape0 projectsTable = Shape0(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 sessionWorktreesTable = Shape1(
    source: i0.VersionedTable(
      entityName: 'session_worktrees_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [_column_4, _column_0, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get hidden =>
      columnsByName['hidden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get worktreeCounter =>
      columnsByName['worktree_counter']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'project_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'hidden',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (hidden IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'base_branch',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'worktree_counter',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get worktreePath =>
      columnsByName['worktree_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'worktree_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'branch_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
  ];
  late final Shape0 projectsTable = Shape0(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 sessionsTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_0,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get worktreePath =>
      columnsByName['worktree_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDedicated =>
      columnsByName['is_dedicated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseCommit =>
      columnsByName['base_commit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'worktree_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'branch_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_dedicated',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_dedicated IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archived_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'base_commit',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    pullRequestsTable,
  ];
  late final Shape0 projectsTable = Shape0(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 sessionsTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_0,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pullRequestsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, pr_number)'],
      columns: [
        _column_13,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get prNumber =>
      columnsByName['pr_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mergeableStatus =>
      columnsByName['mergeable_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reviewDecision =>
      columnsByName['review_decision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get checkStatus =>
      columnsByName['check_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastCheckedAt =>
      columnsByName['last_checked_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'project_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES projects_table(project_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pr_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mergeable_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'review_decision',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'check_status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_checked_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    pullRequestsTable,
  ];
  late final Shape0 projectsTable = Shape0(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 sessionsTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_13,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pullRequestsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, pr_number)'],
      columns: [
        _column_13,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    pullRequestsTable,
  ];
  late final Shape0 projectsTable = Shape0(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 sessionsTable = Shape4(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_13,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pullRequestsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, pr_number)'],
      columns: [
        _column_13,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get worktreePath =>
      columnsByName['worktree_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDedicated =>
      columnsByName['is_dedicated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseCommit =>
      columnsByName['base_commit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgent =>
      columnsByName['last_agent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgentModel =>
      columnsByName['last_agent_model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_agent',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_agent_model',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    pullRequestsTable,
  ];
  late final Shape0 projectsTable = Shape0(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 sessionsTable = Shape5(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_13,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
        _column_24,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pullRequestsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, pr_number)'],
      columns: [
        _column_13,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get worktreePath =>
      columnsByName['worktree_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDedicated =>
      columnsByName['is_dedicated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseCommit =>
      columnsByName['base_commit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgent =>
      columnsByName['last_agent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgentModel =>
      columnsByName['last_agent_model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastActivityAt =>
      columnsByName['last_activity_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSeenAt =>
      columnsByName['last_seen_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastUserMessageAt =>
      columnsByName['last_user_message_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_activity_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_seen_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_user_message_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    pullRequestsTable,
  ];
  late final Shape6 projectsTable = Shape6(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [
        _column_0,
        _column_27,
        _column_1,
        _column_2,
        _column_3,
        _column_28,
        _column_29,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 sessionsTable = Shape7(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_13,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
        _column_24,
        _column_25,
        _column_26,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pullRequestsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, pr_number)'],
      columns: [
        _column_13,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get hidden =>
      columnsByName['hidden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get worktreeCounter =>
      columnsByName['worktree_counter']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get openedAt =>
      columnsByName['opened_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'opened_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get worktreePath =>
      columnsByName['worktree_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDedicated =>
      columnsByName['is_dedicated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseCommit =>
      columnsByName['base_commit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgent =>
      columnsByName['last_agent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgentModel =>
      columnsByName['last_agent_model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastActivityAt =>
      columnsByName['last_activity_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSeenAt =>
      columnsByName['last_seen_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastUserMessageAt =>
      columnsByName['last_user_message_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plugin_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema9 extends i0.VersionedSchema {
  Schema9({required super.database}) : super(version: 9);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    pullRequestsTable,
  ];
  late final Shape8 projectsTable = Shape8(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [
        _column_0,
        _column_27,
        _column_1,
        _column_2,
        _column_3,
        _column_28,
        _column_12,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 sessionsTable = Shape7(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_13,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
        _column_24,
        _column_25,
        _column_26,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pullRequestsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, pr_number)'],
      columns: [
        _column_13,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get hidden =>
      columnsByName['hidden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get worktreeCounter =>
      columnsByName['worktree_counter']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema10 extends i0.VersionedSchema {
  Schema10({required super.database}) : super(version: 10);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    deletedSessionsTable,
    pullRequestsTable,
  ];
  late final Shape8 projectsTable = Shape8(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [
        _column_0,
        _column_27,
        _column_1,
        _column_2,
        _column_3,
        _column_28,
        _column_12,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 sessionsTable = Shape9(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_13,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
        _column_24,
        _column_25,
        _column_26,
        _column_30,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 deletedSessionsTable = Shape10(
    source: i0.VersionedTable(
      entityName: 'deleted_sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(owner_identity, plugin_id, session_id)'],
      columns: [_column_33, _column_4, _column_30, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pullRequestsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, pr_number)'],
      columns: [
        _column_13,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get worktreePath =>
      columnsByName['worktree_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDedicated =>
      columnsByName['is_dedicated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseCommit =>
      columnsByName['base_commit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgent =>
      columnsByName['last_agent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgentModel =>
      columnsByName['last_agent_model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastActivityAt =>
      columnsByName['last_activity_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSeenAt =>
      columnsByName['last_seen_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastUserMessageAt =>
      columnsByName['last_user_message_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get ownerIdentity =>
      columnsByName['owner_identity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner_identity',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'local\'',
      defaultValue: const i1.CustomExpression('\'local\''),
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema11 extends i0.VersionedSchema {
  Schema11({required super.database}) : super(version: 11);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    deletedSessionsTable,
    pullRequestsTable,
    catalogHydrationsTable,
    idxProjectsPath,
    idxProjectsUpdated,
    idxSessionsPluginBackend,
    idxSessionsRoots,
    idxSessionsChildren,
    idxSessionsArchive,
  ];
  late final Shape11 projectsTable = Shape11(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [
        _column_0,
        _column_27,
        _column_1,
        _column_2,
        _column_28,
        _column_12,
        _column_31,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 sessionsTable = Shape12(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_36,
        _column_13,
        _column_37,
        _column_38,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
        _column_31,
        _column_35,
        _column_24,
        _column_25,
        _column_26,
        _column_30,
        _column_32,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 deletedSessionsTable = Shape13(
    source: i0.VersionedTable(
      entityName: 'deleted_sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(owner_identity, plugin_id, backend_session_id)',
      ],
      columns: [_column_33, _column_36, _column_30, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pullRequestsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, pr_number)'],
      columns: [
        _column_13,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 catalogHydrationsTable = Shape14(
    source: i0.VersionedTable(
      entityName: 'catalog_hydrations_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, projection_version)'],
      columns: [_column_30, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProjectsPath = i1.Index(
    'idx_projects_path',
    'CREATE INDEX idx_projects_path ON projects_table (path)',
  );
  final i1.Index idxProjectsUpdated = i1.Index(
    'idx_projects_updated',
    'CREATE INDEX idx_projects_updated ON projects_table (updated_at DESC, project_id DESC)',
  );
  final i1.Index idxSessionsPluginBackend = i1.Index(
    'idx_sessions_plugin_backend',
    'CREATE UNIQUE INDEX idx_sessions_plugin_backend ON sessions_table (plugin_id, backend_session_id)',
  );
  final i1.Index idxSessionsRoots = i1.Index(
    'idx_sessions_roots',
    'CREATE INDEX idx_sessions_roots ON sessions_table (project_id, parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsChildren = i1.Index(
    'idx_sessions_children',
    'CREATE INDEX idx_sessions_children ON sessions_table (parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsArchive = i1.Index(
    'idx_sessions_archive',
    'CREATE INDEX idx_sessions_archive ON sessions_table (updated_at DESC, session_id DESC) WHERE archived_at IS NOT NULL',
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get hidden =>
      columnsByName['hidden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get projectionUpdatedAt =>
      columnsByName['projection_updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'projection_updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get backendSessionId =>
      columnsByName['backend_session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parentSessionId =>
      columnsByName['parent_session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get directory =>
      columnsByName['directory']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get worktreePath =>
      columnsByName['worktree_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDedicated =>
      columnsByName['is_dedicated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseCommit =>
      columnsByName['base_commit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgent =>
      columnsByName['last_agent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgentModel =>
      columnsByName['last_agent_model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get projectionUpdatedAt =>
      columnsByName['projection_updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastActivityAt =>
      columnsByName['last_activity_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSeenAt =>
      columnsByName['last_seen_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastUserMessageAt =>
      columnsByName['last_user_message_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catalogTitle =>
      columnsByName['catalog_title']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'backend_session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parent_session_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NULL REFERENCES sessions_table(session_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'directory',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'catalog_title',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get ownerIdentity =>
      columnsByName['owner_identity']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get backendSessionId =>
      columnsByName['backend_session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get projectionVersion =>
      columnsByName['projection_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'projection_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema12 extends i0.VersionedSchema {
  Schema12({required super.database}) : super(version: 12);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    deletedSessionsTable,
    pullRequestsTable,
    catalogHydrationsTable,
    sessionOptionsCacheTable,
    idxProjectsPath,
    idxProjectsUpdated,
    idxSessionsPluginBackend,
    idxSessionsRoots,
    idxSessionsChildren,
    idxSessionsArchive,
  ];
  late final Shape11 projectsTable = Shape11(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [
        _column_0,
        _column_27,
        _column_1,
        _column_2,
        _column_28,
        _column_12,
        _column_31,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 sessionsTable = Shape12(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_36,
        _column_13,
        _column_37,
        _column_38,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
        _column_31,
        _column_35,
        _column_24,
        _column_25,
        _column_26,
        _column_30,
        _column_32,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 deletedSessionsTable = Shape13(
    source: i0.VersionedTable(
      entityName: 'deleted_sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(owner_identity, plugin_id, backend_session_id)',
      ],
      columns: [_column_33, _column_36, _column_30, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 pullRequestsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id, pr_number)'],
      columns: [
        _column_13,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 catalogHydrationsTable = Shape14(
    source: i0.VersionedTable(
      entityName: 'catalog_hydrations_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, projection_version)'],
      columns: [_column_30, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 sessionOptionsCacheTable = Shape15(
    source: i0.VersionedTable(
      entityName: 'session_options_cache_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(plugin_id, scope, owner_id)',
        'CHECK(owner_id <> \'\' AND((scope = \'plugin\' AND project_id IS NULL AND captured_project_path IS NULL)OR(scope = \'project\' AND project_id IS NOT NULL AND owner_id = project_id AND captured_project_path IS NOT NULL AND captured_project_path <> \'\')))',
      ],
      columns: [
        _column_30,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProjectsPath = i1.Index(
    'idx_projects_path',
    'CREATE INDEX idx_projects_path ON projects_table (path)',
  );
  final i1.Index idxProjectsUpdated = i1.Index(
    'idx_projects_updated',
    'CREATE INDEX idx_projects_updated ON projects_table (updated_at DESC, project_id DESC)',
  );
  final i1.Index idxSessionsPluginBackend = i1.Index(
    'idx_sessions_plugin_backend',
    'CREATE UNIQUE INDEX idx_sessions_plugin_backend ON sessions_table (plugin_id, backend_session_id)',
  );
  final i1.Index idxSessionsRoots = i1.Index(
    'idx_sessions_roots',
    'CREATE INDEX idx_sessions_roots ON sessions_table (project_id, parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsChildren = i1.Index(
    'idx_sessions_children',
    'CREATE INDEX idx_sessions_children ON sessions_table (parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsArchive = i1.Index(
    'idx_sessions_archive',
    'CREATE INDEX idx_sessions_archive ON sessions_table (updated_at DESC, session_id DESC) WHERE archived_at IS NOT NULL',
  );
}

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scope =>
      columnsByName['scope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerId =>
      columnsByName['owner_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get capturedProjectPath =>
      columnsByName['captured_project_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get revision =>
      columnsByName['revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get capturedAt =>
      columnsByName['captured_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get completeness =>
      columnsByName['completeness']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get agentsJson =>
      columnsByName['agents_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providersJson =>
      columnsByName['providers_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get commandsJson =>
      columnsByName['commands_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scope',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'project_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NULL REFERENCES projects_table(project_id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'captured_project_path',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'captured_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'completeness',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'agents_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'providers_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'commands_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema13 extends i0.VersionedSchema {
  Schema13({required super.database}) : super(version: 13);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    deletedSessionsTable,
    pullRequestsTable,
    catalogHydrationsTable,
    sessionOptionsCacheTable,
    idxProjectsPath,
    idxProjectsUpdated,
    idxSessionsPluginBackend,
    idxSessionsRoots,
    idxSessionsChildren,
    idxSessionsArchive,
    idxPullRequestsScope,
  ];
  late final Shape16 projectsTable = Shape16(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [
        _column_0,
        _column_27,
        _column_1,
        _column_2,
        _column_52,
        _column_28,
        _column_12,
        _column_31,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 sessionsTable = Shape17(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_36,
        _column_13,
        _column_37,
        _column_38,
        _column_7,
        _column_8,
        _column_53,
        _column_54,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
        _column_31,
        _column_35,
        _column_24,
        _column_25,
        _column_26,
        _column_30,
        _column_32,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 deletedSessionsTable = Shape13(
    source: i0.VersionedTable(
      entityName: 'deleted_sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(owner_identity, plugin_id, backend_session_id)',
      ],
      columns: [_column_33, _column_36, _column_30, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 pullRequestsTable = Shape18(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(project_id, github_repository_identity, pr_number)',
      ],
      columns: [
        _column_13,
        _column_55,
        _column_56,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 catalogHydrationsTable = Shape14(
    source: i0.VersionedTable(
      entityName: 'catalog_hydrations_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, projection_version)'],
      columns: [_column_30, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 sessionOptionsCacheTable = Shape15(
    source: i0.VersionedTable(
      entityName: 'session_options_cache_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(plugin_id, scope, owner_id)',
        'CHECK(owner_id <> \'\' AND((scope = \'plugin\' AND project_id IS NULL AND captured_project_path IS NULL)OR(scope = \'project\' AND project_id IS NOT NULL AND owner_id = project_id AND captured_project_path IS NOT NULL AND captured_project_path <> \'\')))',
      ],
      columns: [
        _column_30,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProjectsPath = i1.Index(
    'idx_projects_path',
    'CREATE INDEX idx_projects_path ON projects_table (path)',
  );
  final i1.Index idxProjectsUpdated = i1.Index(
    'idx_projects_updated',
    'CREATE INDEX idx_projects_updated ON projects_table (updated_at DESC, project_id DESC)',
  );
  final i1.Index idxSessionsPluginBackend = i1.Index(
    'idx_sessions_plugin_backend',
    'CREATE UNIQUE INDEX idx_sessions_plugin_backend ON sessions_table (plugin_id, backend_session_id)',
  );
  final i1.Index idxSessionsRoots = i1.Index(
    'idx_sessions_roots',
    'CREATE INDEX idx_sessions_roots ON sessions_table (project_id, parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsChildren = i1.Index(
    'idx_sessions_children',
    'CREATE INDEX idx_sessions_children ON sessions_table (parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsArchive = i1.Index(
    'idx_sessions_archive',
    'CREATE INDEX idx_sessions_archive ON sessions_table (updated_at DESC, session_id DESC) WHERE archived_at IS NOT NULL',
  );
  final i1.Index idxPullRequestsScope = i1.Index(
    'idx_pull_requests_scope',
    'CREATE INDEX idx_pull_requests_scope ON pull_requests_table (project_id, github_repository_identity, branch_name, github_login)',
  );
}

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get path =>
      columnsByName['path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get hidden =>
      columnsByName['hidden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get prCacheGithubLogin =>
      columnsByName['pr_cache_github_login']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get projectionUpdatedAt =>
      columnsByName['projection_updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pr_cache_github_login',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get backendSessionId =>
      columnsByName['backend_session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parentSessionId =>
      columnsByName['parent_session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get directory =>
      columnsByName['directory']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get worktreePath =>
      columnsByName['worktree_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currentBranchName =>
      columnsByName['current_branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get currentGithubRepositoryIdentity =>
      columnsByName['current_github_repository_identity']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDedicated =>
      columnsByName['is_dedicated']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get archivedAt =>
      columnsByName['archived_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get baseBranch =>
      columnsByName['base_branch']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseCommit =>
      columnsByName['base_commit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgent =>
      columnsByName['last_agent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAgentModel =>
      columnsByName['last_agent_model']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get projectionUpdatedAt =>
      columnsByName['projection_updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastActivityAt =>
      columnsByName['last_activity_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastSeenAt =>
      columnsByName['last_seen_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get lastUserMessageAt =>
      columnsByName['last_user_message_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catalogTitle =>
      columnsByName['catalog_title']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'current_branch_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'current_github_repository_identity',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get githubRepositoryIdentity =>
      columnsByName['github_repository_identity']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get githubLogin =>
      columnsByName['github_login']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get prNumber =>
      columnsByName['pr_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get branchName =>
      columnsByName['branch_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mergeableStatus =>
      columnsByName['mergeable_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reviewDecision =>
      columnsByName['review_decision']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get checkStatus =>
      columnsByName['check_status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastCheckedAt =>
      columnsByName['last_checked_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'github_repository_identity',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'github_login',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema14 extends i0.VersionedSchema {
  Schema14({required super.database}) : super(version: 14);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    deletedSessionsTable,
    pullRequestsTable,
    catalogHydrationsTable,
    sessionOptionsCacheTable,
    newSessionDefaultsTable,
    idxProjectsPath,
    idxProjectsUpdated,
    idxSessionsPluginBackend,
    idxSessionsRoots,
    idxSessionsChildren,
    idxSessionsArchive,
    idxPullRequestsScope,
  ];
  late final Shape16 projectsTable = Shape16(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [
        _column_0,
        _column_27,
        _column_1,
        _column_2,
        _column_52,
        _column_28,
        _column_12,
        _column_31,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 sessionsTable = Shape17(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_36,
        _column_13,
        _column_37,
        _column_38,
        _column_7,
        _column_8,
        _column_53,
        _column_54,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
        _column_31,
        _column_35,
        _column_24,
        _column_25,
        _column_26,
        _column_30,
        _column_32,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 deletedSessionsTable = Shape13(
    source: i0.VersionedTable(
      entityName: 'deleted_sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(owner_identity, plugin_id, backend_session_id)',
      ],
      columns: [_column_33, _column_36, _column_30, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 pullRequestsTable = Shape18(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(project_id, github_repository_identity, pr_number)',
      ],
      columns: [
        _column_13,
        _column_55,
        _column_56,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 catalogHydrationsTable = Shape14(
    source: i0.VersionedTable(
      entityName: 'catalog_hydrations_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, projection_version)'],
      columns: [_column_30, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 sessionOptionsCacheTable = Shape15(
    source: i0.VersionedTable(
      entityName: 'session_options_cache_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(plugin_id, scope, owner_id)',
        'CHECK(owner_id <> \'\' AND((scope = \'plugin\' AND project_id IS NULL AND captured_project_path IS NULL)OR(scope = \'project\' AND project_id IS NOT NULL AND owner_id = project_id AND captured_project_path IS NOT NULL AND captured_project_path <> \'\')))',
      ],
      columns: [
        _column_30,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 newSessionDefaultsTable = Shape19(
    source: i0.VersionedTable(
      entityName: 'new_session_defaults_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id)', 'CHECK(plugin_id <> \'\')'],
      columns: [_column_30, _column_57, _column_58],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProjectsPath = i1.Index(
    'idx_projects_path',
    'CREATE INDEX idx_projects_path ON projects_table (path)',
  );
  final i1.Index idxProjectsUpdated = i1.Index(
    'idx_projects_updated',
    'CREATE INDEX idx_projects_updated ON projects_table (updated_at DESC, project_id DESC)',
  );
  final i1.Index idxSessionsPluginBackend = i1.Index(
    'idx_sessions_plugin_backend',
    'CREATE UNIQUE INDEX idx_sessions_plugin_backend ON sessions_table (plugin_id, backend_session_id)',
  );
  final i1.Index idxSessionsRoots = i1.Index(
    'idx_sessions_roots',
    'CREATE INDEX idx_sessions_roots ON sessions_table (project_id, parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsChildren = i1.Index(
    'idx_sessions_children',
    'CREATE INDEX idx_sessions_children ON sessions_table (parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsArchive = i1.Index(
    'idx_sessions_archive',
    'CREATE INDEX idx_sessions_archive ON sessions_table (updated_at DESC, session_id DESC) WHERE archived_at IS NOT NULL',
  );
  final i1.Index idxPullRequestsScope = i1.Index(
    'idx_pull_requests_scope',
    'CREATE INDEX idx_pull_requests_scope ON pull_requests_table (project_id, github_repository_identity, branch_name, github_login)',
  );
}

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get agent =>
      columnsByName['agent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get agentModel =>
      columnsByName['agent_model']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'agent',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'agent_model',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema15 extends i0.VersionedSchema {
  Schema15({required super.database}) : super(version: 15);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    projectsTable,
    sessionsTable,
    deletedSessionsTable,
    pullRequestsTable,
    catalogHydrationsTable,
    sessionOptionsCacheTable,
    newSessionDefaultsTable,
    idxProjectsPath,
    idxProjectsUpdated,
    idxSessionsPluginBackend,
    idxSessionsRoots,
    idxSessionsChildren,
    idxSessionsArchive,
    idxPullRequestsScope,
  ];
  late final Shape16 projectsTable = Shape16(
    source: i0.VersionedTable(
      entityName: 'projects_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(project_id)'],
      columns: [
        _column_0,
        _column_27,
        _column_1,
        _column_2,
        _column_52,
        _column_28,
        _column_12,
        _column_31,
        _column_35,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 sessionsTable = Shape17(
    source: i0.VersionedTable(
      entityName: 'sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id)'],
      columns: [
        _column_4,
        _column_36,
        _column_13,
        _column_37,
        _column_38,
        _column_7,
        _column_8,
        _column_53,
        _column_54,
        _column_9,
        _column_10,
        _column_2,
        _column_11,
        _column_22,
        _column_23,
        _column_12,
        _column_31,
        _column_35,
        _column_24,
        _column_25,
        _column_26,
        _column_30,
        _column_32,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 deletedSessionsTable = Shape13(
    source: i0.VersionedTable(
      entityName: 'deleted_sessions_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(owner_identity, plugin_id, backend_session_id)',
      ],
      columns: [_column_33, _column_36, _column_30, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 pullRequestsTable = Shape18(
    source: i0.VersionedTable(
      entityName: 'pull_requests_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(project_id, github_repository_identity, pr_number)',
      ],
      columns: [
        _column_13,
        _column_55,
        _column_56,
        _column_14,
        _column_6,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 catalogHydrationsTable = Shape14(
    source: i0.VersionedTable(
      entityName: 'catalog_hydrations_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id, projection_version)'],
      columns: [_column_30, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 sessionOptionsCacheTable = Shape20(
    source: i0.VersionedTable(
      entityName: 'session_options_cache_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(plugin_id, scope, owner_id)',
        'CHECK(owner_id <> \'\' AND((scope = \'plugin\' AND project_id IS NULL AND captured_project_path IS NULL)OR(scope = \'project\' AND project_id IS NOT NULL AND owner_id = project_id AND captured_project_path IS NOT NULL AND captured_project_path <> \'\')))',
      ],
      columns: [
        _column_30,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_49,
        _column_50,
        _column_51,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 newSessionDefaultsTable = Shape19(
    source: i0.VersionedTable(
      entityName: 'new_session_defaults_table',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(plugin_id)', 'CHECK(plugin_id <> \'\')'],
      columns: [_column_30, _column_57, _column_58],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxProjectsPath = i1.Index(
    'idx_projects_path',
    'CREATE INDEX idx_projects_path ON projects_table (path)',
  );
  final i1.Index idxProjectsUpdated = i1.Index(
    'idx_projects_updated',
    'CREATE INDEX idx_projects_updated ON projects_table (updated_at DESC, project_id DESC)',
  );
  final i1.Index idxSessionsPluginBackend = i1.Index(
    'idx_sessions_plugin_backend',
    'CREATE UNIQUE INDEX idx_sessions_plugin_backend ON sessions_table (plugin_id, backend_session_id)',
  );
  final i1.Index idxSessionsRoots = i1.Index(
    'idx_sessions_roots',
    'CREATE INDEX idx_sessions_roots ON sessions_table (project_id, parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsChildren = i1.Index(
    'idx_sessions_children',
    'CREATE INDEX idx_sessions_children ON sessions_table (parent_session_id, updated_at, session_id)',
  );
  final i1.Index idxSessionsArchive = i1.Index(
    'idx_sessions_archive',
    'CREATE INDEX idx_sessions_archive ON sessions_table (updated_at DESC, session_id DESC) WHERE archived_at IS NOT NULL',
  );
  final i1.Index idxPullRequestsScope = i1.Index(
    'idx_pull_requests_scope',
    'CREATE INDEX idx_pull_requests_scope ON pull_requests_table (project_id, github_repository_identity, branch_name, github_login)',
  );
}

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get pluginId =>
      columnsByName['plugin_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scope =>
      columnsByName['scope']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerId =>
      columnsByName['owner_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectId =>
      columnsByName['project_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get capturedProjectPath =>
      columnsByName['captured_project_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get revision =>
      columnsByName['revision']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get capturedAt =>
      columnsByName['captured_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get agentsJson =>
      columnsByName['agents_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providersJson =>
      columnsByName['providers_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get commandsJson =>
      columnsByName['commands_json']! as i1.GeneratedColumn<String>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
  required Future<void> Function(i1.Migrator m, Schema13 schema) from12To13,
  required Future<void> Function(i1.Migrator m, Schema14 schema) from13To14,
  required Future<void> Function(i1.Migrator m, Schema15 schema) from14To15,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      case 8:
        final schema = Schema9(database: database);
        final migrator = i1.Migrator(database, schema);
        await from8To9(migrator, schema);
        return 9;
      case 9:
        final schema = Schema10(database: database);
        final migrator = i1.Migrator(database, schema);
        await from9To10(migrator, schema);
        return 10;
      case 10:
        final schema = Schema11(database: database);
        final migrator = i1.Migrator(database, schema);
        await from10To11(migrator, schema);
        return 11;
      case 11:
        final schema = Schema12(database: database);
        final migrator = i1.Migrator(database, schema);
        await from11To12(migrator, schema);
        return 12;
      case 12:
        final schema = Schema13(database: database);
        final migrator = i1.Migrator(database, schema);
        await from12To13(migrator, schema);
        return 13;
      case 13:
        final schema = Schema14(database: database);
        final migrator = i1.Migrator(database, schema);
        await from13To14(migrator, schema);
        return 14;
      case 14:
        final schema = Schema15(database: database);
        final migrator = i1.Migrator(database, schema);
        await from14To15(migrator, schema);
        return 15;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
  required Future<void> Function(i1.Migrator m, Schema9 schema) from8To9,
  required Future<void> Function(i1.Migrator m, Schema10 schema) from9To10,
  required Future<void> Function(i1.Migrator m, Schema11 schema) from10To11,
  required Future<void> Function(i1.Migrator m, Schema12 schema) from11To12,
  required Future<void> Function(i1.Migrator m, Schema13 schema) from12To13,
  required Future<void> Function(i1.Migrator m, Schema14 schema) from13To14,
  required Future<void> Function(i1.Migrator m, Schema15 schema) from14To15,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
    from7To8: from7To8,
    from8To9: from8To9,
    from9To10: from9To10,
    from10To11: from10To11,
    from11To12: from11To12,
    from12To13: from12To13,
    from13To14: from13To14,
    from14To15: from14To15,
  ),
);
