name: no_slop_linter
description: Linter to prevent sloppy code
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=3.13.0-0 <4.0.0"

dependencies:
  analysis_server_plugin: ">=0.3.18 <0.3.19"
  _fe_analyzer_shared: ">=103.0.0 <104.0.0"
  analyzer: ">=13.3.0 <14.0.0"
  analyzer_plugin: ">=0.14.12 <0.14.13"

dev_dependencies:
  analyzer_testing: ^0.3.2
  dartz: ^0.10.1
  lints: ^6.1.0
  path: ^1.9.1
  test: ^1.30.0
  test_reflective_loader: ^0.4.0
