name: no_slop_linter
description: Linter to prevent sloppy code
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=3.11.5 <4.0.0"

dependencies:
  analysis_server_plugin: ">=0.3.5 <0.4.0" # 0.3.5 works with analyzer 10.0.0
  _fe_analyzer_shared: ">=93.0.0 <99.0.0"
  analyzer: ">=10.0.0 <13.0.0"
  analyzer_plugin: ^0.14.0

dev_dependencies:
  analyzer_testing: ^0.2.1
  dartz: ^0.10.1
  lints: ^6.1.0
  path: ^1.9.1
  test: ^1.30.0
  test_reflective_loader: ^0.4.0
