// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: scripts/generate_icon_font_dart.dart
// ignore_for_file: constant_identifier_names

import "package:flutter/widgets.dart";

/// VESPRLight icon font.
///
/// 4 icons available.
class VESPRLight {
  VESPRLight._();

  static const IconData face_id = IconData(0xE000, fontFamily: "VESPRLight", fontPackage: "theme_zyra");
  static const IconData gear = IconData(0xE001, fontFamily: "VESPRLight", fontPackage: "theme_zyra");
  static const IconData qr_scan = IconData(0xE002, fontFamily: "VESPRLight", fontPackage: "theme_zyra");
  static const IconData wallet = IconData(0xE003, fontFamily: "VESPRLight", fontPackage: "theme_zyra");
}

/// VESPRRegular icon font.
///
/// 4 icons available.
class VESPRRegular {
  VESPRRegular._();

  static const IconData face_id = IconData(0xE000, fontFamily: "VESPRRegular", fontPackage: "theme_zyra");
  static const IconData gear = IconData(0xE001, fontFamily: "VESPRRegular", fontPackage: "theme_zyra");
  static const IconData qr_scan = IconData(0xE002, fontFamily: "VESPRRegular", fontPackage: "theme_zyra");
  static const IconData wallet = IconData(0xE003, fontFamily: "VESPRRegular", fontPackage: "theme_zyra");
}

/// VESPRSolid icon font.
///
/// 15 icons available.
class VESPRSolid {
  VESPRSolid._();

  static const IconData anthopic = IconData(0xE004, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData apple = IconData(0xE005, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData codex = IconData(0xE006, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData cursor = IconData(0xE007, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData discord = IconData(0xE008, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData face_id = IconData(0xE000, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData gear = IconData(0xE001, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData google = IconData(0xE009, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData grok = IconData(0xE010, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData openai = IconData(0xE011, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData opencode = IconData(0xE012, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData qr_scan = IconData(0xE002, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData sesori = IconData(0xE013, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData wallet = IconData(0xE003, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData windows = IconData(0xE014, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
}
