// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: scripts/generate_icon_font_dart.dart
// ignore_for_file: constant_identifier_names

import "package:flutter/widgets.dart";

/// VESPRLight icon font.
///
/// 4 icons available.
class VESPRLight {
  VESPRLight._();

  static const IconData face_id = IconData(0xE000, fontFamily: "VESPRLight", fontPackage: "theme_zyra");
  static const IconData gear = IconData(0xE001, fontFamily: "VESPRLight", fontPackage: "theme_zyra");
  static const IconData qr_scan = IconData(0xE002, fontFamily: "VESPRLight", fontPackage: "theme_zyra");
  static const IconData wallet = IconData(0xE003, fontFamily: "VESPRLight", fontPackage: "theme_zyra");
}

/// VESPRRegular icon font.
///
/// 4 icons available.
class VESPRRegular {
  VESPRRegular._();

  static const IconData face_id = IconData(0xE000, fontFamily: "VESPRRegular", fontPackage: "theme_zyra");
  static const IconData gear = IconData(0xE001, fontFamily: "VESPRRegular", fontPackage: "theme_zyra");
  static const IconData qr_scan = IconData(0xE002, fontFamily: "VESPRRegular", fontPackage: "theme_zyra");
  static const IconData wallet = IconData(0xE003, fontFamily: "VESPRRegular", fontPackage: "theme_zyra");
}

/// VESPRSolid icon font.
///
/// 4 icons available.
class VESPRSolid {
  VESPRSolid._();

  static const IconData face_id = IconData(0xE000, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData gear = IconData(0xE001, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData qr_scan = IconData(0xE002, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
  static const IconData wallet = IconData(0xE003, fontFamily: "VESPRSolid", fontPackage: "theme_zyra");
}
