name: sesori_plugin_runtime
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  path: ^1.9.1
  sesori_bridge_foundation:
    path: ../sesori_bridge_foundation
  sesori_plugin_interface:
    path: ../sesori_plugin_interface

dev_dependencies:
  lints: ^6.1.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  build_runner: any
  test: ^1.31.1
