// GENERATED CODE - DO NOT MODIFY BY HAND
// Run: dart run tool/generate_inspector_tokens.dart
// ignore_for_file: lines_longer_than_80_chars

import "package:flutter/widgets.dart";
import "package:theme_prego/module_prego.dart";
import "package:theme_prego/theme/primitives/prego_color_primitives.g.dart";

import "prego_inspection_tokens.dart";

List<PregoInspectionToken<Color>> buildPregoInspectionColorTokens(PregoColors colors) => [
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-brand-primary", reference: "context.prego.colors.textBrandPrimary", value: colors.textBrandPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-brand-secondary", reference: "context.prego.colors.textBrandSecondary", value: colors.textBrandSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-brand-secondary-hover", reference: "context.prego.colors.textBrandSecondaryHover", value: colors.textBrandSecondaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-brand-tertiary", reference: "context.prego.colors.textBrandTertiary", value: colors.textBrandTertiary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-brand-tertiary-alt", reference: "context.prego.colors.textBrandTertiaryAlt", value: colors.textBrandTertiaryAlt),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-disabled", reference: "context.prego.colors.textDisabled", value: colors.textDisabled),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-error-primary", reference: "context.prego.colors.textErrorPrimary", value: colors.textErrorPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-error-primary-hover", reference: "context.prego.colors.textErrorPrimaryHover", value: colors.textErrorPrimaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-placeholder", reference: "context.prego.colors.textPlaceholder", value: colors.textPlaceholder),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-placeholder-subtle", reference: "context.prego.colors.textPlaceholderSubtle", value: colors.textPlaceholderSubtle),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-primary", reference: "context.prego.colors.textPrimary", value: colors.textPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-primary-on-brand", reference: "context.prego.colors.textPrimaryOnBrand", value: colors.textPrimaryOnBrand),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-primary-on-white", reference: "context.prego.colors.textPrimaryOnWhite", value: colors.textPrimaryOnWhite),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-quaternary", reference: "context.prego.colors.textQuaternary", value: colors.textQuaternary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-secondary", reference: "context.prego.colors.textSecondary", value: colors.textSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-secondary-hover", reference: "context.prego.colors.textSecondaryHover", value: colors.textSecondaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-secondary-on-brand", reference: "context.prego.colors.textSecondaryOnBrand", value: colors.textSecondaryOnBrand),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-success-primary", reference: "context.prego.colors.textSuccessPrimary", value: colors.textSuccessPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-tertiary", reference: "context.prego.colors.textTertiary", value: colors.textTertiary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-tertiary-hover", reference: "context.prego.colors.textTertiaryHover", value: colors.textTertiaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-tertiary-on-brand", reference: "context.prego.colors.textTertiaryOnBrand", value: colors.textTertiaryOnBrand),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-warning-primary", reference: "context.prego.colors.textWarningPrimary", value: colors.textWarningPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "text-white", reference: "context.prego.colors.textWhite", value: colors.textWhite),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-brand", reference: "context.prego.colors.borderBrand", value: colors.borderBrand),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-disabled", reference: "context.prego.colors.borderDisabled", value: colors.borderDisabled),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-disabled-subtle", reference: "context.prego.colors.borderDisabledSubtle", value: colors.borderDisabledSubtle),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-error", reference: "context.prego.colors.borderError", value: colors.borderError),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-error-subtle", reference: "context.prego.colors.borderErrorSubtle", value: colors.borderErrorSubtle),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-inside-reversed-bottom", reference: "context.prego.colors.borderInsideReversedBottom", value: colors.borderInsideReversedBottom),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-inside-reversed-top", reference: "context.prego.colors.borderInsideReversedTop", value: colors.borderInsideReversedTop),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-primary", reference: "context.prego.colors.borderPrimary", value: colors.borderPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-reversed", reference: "context.prego.colors.borderReversed", value: colors.borderReversed),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-secondary", reference: "context.prego.colors.borderSecondary", value: colors.borderSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-secondary-alt", reference: "context.prego.colors.borderSecondaryAlt", value: colors.borderSecondaryAlt),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-selected", reference: "context.prego.colors.borderSelected", value: colors.borderSelected),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "border-tertiary", reference: "context.prego.colors.borderTertiary", value: colors.borderTertiary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-brand-primary", reference: "context.prego.colors.fgBrandPrimary", value: colors.fgBrandPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-brand-primary-alt", reference: "context.prego.colors.fgBrandPrimaryAlt", value: colors.fgBrandPrimaryAlt),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-brand-secondary", reference: "context.prego.colors.fgBrandSecondary", value: colors.fgBrandSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-brand-secondary-alt", reference: "context.prego.colors.fgBrandSecondaryAlt", value: colors.fgBrandSecondaryAlt),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-brand-secondary-hover", reference: "context.prego.colors.fgBrandSecondaryHover", value: colors.fgBrandSecondaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-disabled", reference: "context.prego.colors.fgDisabled", value: colors.fgDisabled),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-disabled-subtle", reference: "context.prego.colors.fgDisabledSubtle", value: colors.fgDisabledSubtle),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-error-primary", reference: "context.prego.colors.fgErrorPrimary", value: colors.fgErrorPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-error-secondary", reference: "context.prego.colors.fgErrorSecondary", value: colors.fgErrorSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-primary", reference: "context.prego.colors.fgPrimary", value: colors.fgPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-quaternary", reference: "context.prego.colors.fgQuaternary", value: colors.fgQuaternary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-quaternary-hover", reference: "context.prego.colors.fgQuaternaryHover", value: colors.fgQuaternaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-secondary", reference: "context.prego.colors.fgSecondary", value: colors.fgSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-secondary-hover", reference: "context.prego.colors.fgSecondaryHover", value: colors.fgSecondaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-success-primary", reference: "context.prego.colors.fgSuccessPrimary", value: colors.fgSuccessPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-success-secondary", reference: "context.prego.colors.fgSuccessSecondary", value: colors.fgSuccessSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-tertiary", reference: "context.prego.colors.fgTertiary", value: colors.fgTertiary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-tertiary-hover", reference: "context.prego.colors.fgTertiaryHover", value: colors.fgTertiaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-warning-primary", reference: "context.prego.colors.fgWarningPrimary", value: colors.fgWarningPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-warning-secondary", reference: "context.prego.colors.fgWarningSecondary", value: colors.fgWarningSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "fg-white", reference: "context.prego.colors.fgWhite", value: colors.fgWhite),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "black-white-inversed", reference: "context.prego.colors.blackWhiteInversed", value: colors.blackWhiteInversed),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-active", reference: "context.prego.colors.bgActive", value: colors.bgActive),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-brand-primary", reference: "context.prego.colors.bgBrandPrimary", value: colors.bgBrandPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-brand-primary-alt", reference: "context.prego.colors.bgBrandPrimaryAlt", value: colors.bgBrandPrimaryAlt),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-brand-secondary", reference: "context.prego.colors.bgBrandSecondary", value: colors.bgBrandSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-brand-section", reference: "context.prego.colors.bgBrandSection", value: colors.bgBrandSection),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-brand-section-subtle", reference: "context.prego.colors.bgBrandSectionSubtle", value: colors.bgBrandSectionSubtle),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-brand-solid", reference: "context.prego.colors.bgBrandSolid", value: colors.bgBrandSolid),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-brand-solid-hover", reference: "context.prego.colors.bgBrandSolidHover", value: colors.bgBrandSolidHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-brand-hover", reference: "context.prego.colors.bgBrandHover", value: colors.bgBrandHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-brand-pressed", reference: "context.prego.colors.bgBrandPressed", value: colors.bgBrandPressed),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-destructive-hover", reference: "context.prego.colors.bgDestructiveHover", value: colors.bgDestructiveHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-destructive-pressed", reference: "context.prego.colors.bgDestructivePressed", value: colors.bgDestructivePressed),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-disabled", reference: "context.prego.colors.bgDisabled", value: colors.bgDisabled),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-disabled-subtle", reference: "context.prego.colors.bgDisabledSubtle", value: colors.bgDisabledSubtle),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-error-primary", reference: "context.prego.colors.bgErrorPrimary", value: colors.bgErrorPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-error-secondary", reference: "context.prego.colors.bgErrorSecondary", value: colors.bgErrorSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-error-solid", reference: "context.prego.colors.bgErrorSolid", value: colors.bgErrorSolid),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-error-solid-hover", reference: "context.prego.colors.bgErrorSolidHover", value: colors.bgErrorSolidHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-gray-hover", reference: "context.prego.colors.bgGrayHover", value: colors.bgGrayHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-gray-pressed", reference: "context.prego.colors.bgGrayPressed", value: colors.bgGrayPressed),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-primary-solid", reference: "context.prego.colors.bgPrimarySolid", value: colors.bgPrimarySolid),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-quaternary", reference: "context.prego.colors.bgQuaternary", value: colors.bgQuaternary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-secondary", reference: "context.prego.colors.bgSecondary", value: colors.bgSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-secondary-solid", reference: "context.prego.colors.bgSecondarySolid", value: colors.bgSecondarySolid),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-secondary-alt", reference: "context.prego.colors.bgSecondaryAlt", value: colors.bgSecondaryAlt),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-secondary-hover", reference: "context.prego.colors.bgSecondaryHover", value: colors.bgSecondaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-secondary-subtle", reference: "context.prego.colors.bgSecondarySubtle", value: colors.bgSecondarySubtle),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-success-primary", reference: "context.prego.colors.bgSuccessPrimary", value: colors.bgSuccessPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-success-secondary", reference: "context.prego.colors.bgSuccessSecondary", value: colors.bgSuccessSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-success-solid", reference: "context.prego.colors.bgSuccessSolid", value: colors.bgSuccessSolid),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-surface1", reference: "context.prego.colors.bgSurface1", value: colors.bgSurface1),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-surface2", reference: "context.prego.colors.bgSurface2", value: colors.bgSurface2),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-surface3", reference: "context.prego.colors.bgSurface3", value: colors.bgSurface3),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-surface4", reference: "context.prego.colors.bgSurface4", value: colors.bgSurface4),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-surface5", reference: "context.prego.colors.bgSurface5", value: colors.bgSurface5),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-surface6", reference: "context.prego.colors.bgSurface6", value: colors.bgSurface6),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-surface7", reference: "context.prego.colors.bgSurface7", value: colors.bgSurface7),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-surface8", reference: "context.prego.colors.bgSurface8", value: colors.bgSurface8),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-tertiary", reference: "context.prego.colors.bgTertiary", value: colors.bgTertiary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-warning-primary", reference: "context.prego.colors.bgWarningPrimary", value: colors.bgWarningPrimary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-warning-secondary", reference: "context.prego.colors.bgWarningSecondary", value: colors.bgWarningSecondary),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-warning-solid", reference: "context.prego.colors.bgWarningSolid", value: colors.bgWarningSolid),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-destructive-hover-alt", reference: "context.prego.colors.bgDestructiveHoverAlt", value: colors.bgDestructiveHoverAlt),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "bg-destructive-pressed-alt", reference: "context.prego.colors.bgDestructivePressedAlt", value: colors.bgDestructivePressedAlt),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "focus-ring", reference: "context.prego.colors.focusRing", value: colors.focusRing),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "focus-ring-error", reference: "context.prego.colors.focusRingError", value: colors.focusRingError),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow2xl01", reference: "context.prego.colors.shadow2xl01", value: colors.shadow2xl01),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow2xl02", reference: "context.prego.colors.shadow2xl02", value: colors.shadow2xl02),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow3xl01", reference: "context.prego.colors.shadow3xl01", value: colors.shadow3xl01),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow3xl02", reference: "context.prego.colors.shadow3xl02", value: colors.shadow3xl02),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-cards", reference: "context.prego.colors.shadowCards", value: colors.shadowCards),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-inversed", reference: "context.prego.colors.shadowInversed", value: colors.shadowInversed),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-lg01", reference: "context.prego.colors.shadowLg01", value: colors.shadowLg01),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-lg02", reference: "context.prego.colors.shadowLg02", value: colors.shadowLg02),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-lg03", reference: "context.prego.colors.shadowLg03", value: colors.shadowLg03),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-md01", reference: "context.prego.colors.shadowMd01", value: colors.shadowMd01),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-md02", reference: "context.prego.colors.shadowMd02", value: colors.shadowMd02),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "skeuomorphic-shadow", reference: "context.prego.colors.skeuomorphicShadow", value: colors.skeuomorphicShadow),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "skeuomorphic-inner-border", reference: "context.prego.colors.skeuomorphicInnerBorder", value: colors.skeuomorphicInnerBorder),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-sm01", reference: "context.prego.colors.shadowSm01", value: colors.shadowSm01),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-sm02", reference: "context.prego.colors.shadowSm02", value: colors.shadowSm02),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-xl01", reference: "context.prego.colors.shadowXl01", value: colors.shadowXl01),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-xl02", reference: "context.prego.colors.shadowXl02", value: colors.shadowXl02),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-xl03", reference: "context.prego.colors.shadowXl03", value: colors.shadowXl03),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "shadow-xs", reference: "context.prego.colors.shadowXs", value: colors.shadowXs),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "button-destructive-primary-icon", reference: "context.prego.colors.buttonDestructivePrimaryIcon", value: colors.buttonDestructivePrimaryIcon),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "button-destructive-primary-icon-hover", reference: "context.prego.colors.buttonDestructivePrimaryIconHover", value: colors.buttonDestructivePrimaryIconHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "button-glass-primary-background", reference: "context.prego.colors.buttonGlassPrimaryBackground", value: colors.buttonGlassPrimaryBackground),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "button-glass-primary-hover", reference: "context.prego.colors.buttonGlassPrimaryHover", value: colors.buttonGlassPrimaryHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "button-primary-icon", reference: "context.prego.colors.buttonPrimaryIcon", value: colors.buttonPrimaryIcon),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "button-primary-icon-hover", reference: "context.prego.colors.buttonPrimaryIconHover", value: colors.buttonPrimaryIconHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "icon-fg-brand", reference: "context.prego.colors.iconFgBrand", value: colors.iconFgBrand),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "icon-fg-brand-on-brand", reference: "context.prego.colors.iconFgBrandOnBrand", value: colors.iconFgBrandOnBrand),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black10", reference: "context.prego.colors.alphaBlack10", value: colors.alphaBlack10),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black20", reference: "context.prego.colors.alphaBlack20", value: colors.alphaBlack20),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black30", reference: "context.prego.colors.alphaBlack30", value: colors.alphaBlack30),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black40", reference: "context.prego.colors.alphaBlack40", value: colors.alphaBlack40),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black50", reference: "context.prego.colors.alphaBlack50", value: colors.alphaBlack50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black60", reference: "context.prego.colors.alphaBlack60", value: colors.alphaBlack60),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black70", reference: "context.prego.colors.alphaBlack70", value: colors.alphaBlack70),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black80", reference: "context.prego.colors.alphaBlack80", value: colors.alphaBlack80),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black90", reference: "context.prego.colors.alphaBlack90", value: colors.alphaBlack90),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-black100", reference: "context.prego.colors.alphaBlack100", value: colors.alphaBlack100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white10", reference: "context.prego.colors.alphaWhite10", value: colors.alphaWhite10),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white20", reference: "context.prego.colors.alphaWhite20", value: colors.alphaWhite20),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white30", reference: "context.prego.colors.alphaWhite30", value: colors.alphaWhite30),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white40", reference: "context.prego.colors.alphaWhite40", value: colors.alphaWhite40),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white50", reference: "context.prego.colors.alphaWhite50", value: colors.alphaWhite50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white60", reference: "context.prego.colors.alphaWhite60", value: colors.alphaWhite60),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white70", reference: "context.prego.colors.alphaWhite70", value: colors.alphaWhite70),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white80", reference: "context.prego.colors.alphaWhite80", value: colors.alphaWhite80),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white90", reference: "context.prego.colors.alphaWhite90", value: colors.alphaWhite90),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "alpha-white100", reference: "context.prego.colors.alphaWhite100", value: colors.alphaWhite100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-blue50", reference: "context.prego.colors.utilityBlue50", value: colors.utilityBlue50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-blue100", reference: "context.prego.colors.utilityBlue100", value: colors.utilityBlue100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-blue200", reference: "context.prego.colors.utilityBlue200", value: colors.utilityBlue200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-blue300", reference: "context.prego.colors.utilityBlue300", value: colors.utilityBlue300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-blue400", reference: "context.prego.colors.utilityBlue400", value: colors.utilityBlue400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-blue500", reference: "context.prego.colors.utilityBlue500", value: colors.utilityBlue500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-blue600", reference: "context.prego.colors.utilityBlue600", value: colors.utilityBlue600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-blue700", reference: "context.prego.colors.utilityBlue700", value: colors.utilityBlue700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-error50", reference: "context.prego.colors.utilityError50", value: colors.utilityError50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-error100", reference: "context.prego.colors.utilityError100", value: colors.utilityError100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-error200", reference: "context.prego.colors.utilityError200", value: colors.utilityError200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-error300", reference: "context.prego.colors.utilityError300", value: colors.utilityError300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-error400", reference: "context.prego.colors.utilityError400", value: colors.utilityError400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-error500", reference: "context.prego.colors.utilityError500", value: colors.utilityError500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-error600", reference: "context.prego.colors.utilityError600", value: colors.utilityError600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-error700", reference: "context.prego.colors.utilityError700", value: colors.utilityError700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-success50", reference: "context.prego.colors.utilitySuccess50", value: colors.utilitySuccess50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-success100", reference: "context.prego.colors.utilitySuccess100", value: colors.utilitySuccess100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-success200", reference: "context.prego.colors.utilitySuccess200", value: colors.utilitySuccess200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-success300", reference: "context.prego.colors.utilitySuccess300", value: colors.utilitySuccess300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-success400", reference: "context.prego.colors.utilitySuccess400", value: colors.utilitySuccess400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-success500", reference: "context.prego.colors.utilitySuccess500", value: colors.utilitySuccess500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-success600", reference: "context.prego.colors.utilitySuccess600", value: colors.utilitySuccess600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-success700", reference: "context.prego.colors.utilitySuccess700", value: colors.utilitySuccess700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-warning50", reference: "context.prego.colors.utilityWarning50", value: colors.utilityWarning50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-warning100", reference: "context.prego.colors.utilityWarning100", value: colors.utilityWarning100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-warning200", reference: "context.prego.colors.utilityWarning200", value: colors.utilityWarning200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-warning300", reference: "context.prego.colors.utilityWarning300", value: colors.utilityWarning300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-warning400", reference: "context.prego.colors.utilityWarning400", value: colors.utilityWarning400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-warning500", reference: "context.prego.colors.utilityWarning500", value: colors.utilityWarning500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-warning600", reference: "context.prego.colors.utilityWarning600", value: colors.utilityWarning600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "utility-warning700", reference: "context.prego.colors.utilityWarning700", value: colors.utilityWarning700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "avatar-styles-bg-neutral", reference: "context.prego.colors.avatarStylesBgNeutral", value: colors.avatarStylesBgNeutral),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "brand-gradient-bottom", reference: "context.prego.colors.brandGradientBottom", value: colors.brandGradientBottom),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "brand-gradient-top", reference: "context.prego.colors.brandGradientTop", value: colors.brandGradientTop),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "featured-icon-light-fg-brand", reference: "context.prego.colors.featuredIconLightFgBrand", value: colors.featuredIconLightFgBrand),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "featured-icon-light-fg-error", reference: "context.prego.colors.featuredIconLightFgError", value: colors.featuredIconLightFgError),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "featured-icon-light-fg-gray", reference: "context.prego.colors.featuredIconLightFgGray", value: colors.featuredIconLightFgGray),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "featured-icon-light-fg-success", reference: "context.prego.colors.featuredIconLightFgSuccess", value: colors.featuredIconLightFgSuccess),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "featured-icon-light-fg-warning", reference: "context.prego.colors.featuredIconLightFgWarning", value: colors.featuredIconLightFgWarning),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "green-gradient-bottom", reference: "context.prego.colors.greenGradientBottom", value: colors.greenGradientBottom),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "green-gradient-top2", reference: "context.prego.colors.greenGradientTop2", value: colors.greenGradientTop2),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "orange-gradient-bottom", reference: "context.prego.colors.orangeGradientBottom", value: colors.orangeGradientBottom),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "orange-gradient-top", reference: "context.prego.colors.orangeGradientTop", value: colors.orangeGradientTop),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "purple-gradient-bottom", reference: "context.prego.colors.purpleGradientBottom", value: colors.purpleGradientBottom),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "purple-gradient-top", reference: "context.prego.colors.purpleGradientTop", value: colors.purpleGradientTop),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "toggle-border", reference: "context.prego.colors.toggleBorder", value: colors.toggleBorder),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "toggle-button-fg-disabled", reference: "context.prego.colors.toggleButtonFgDisabled", value: colors.toggleButtonFgDisabled),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "toggle-slim-border-pressed", reference: "context.prego.colors.toggleSlimBorderPressed", value: colors.toggleSlimBorderPressed),
  PregoInspectionToken(kind: PregoInspectionTokenKind.semanticColor, name: "toggle-slim-border-pressed-hover", reference: "context.prego.colors.toggleSlimBorderPressedHover", value: colors.toggleSlimBorderPressedHover),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "base-white", reference: "PregoColorPrimitives.baseWhite", value: PregoColorPrimitives.baseWhite),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "base-black", reference: "PregoColorPrimitives.baseBlack", value: PregoColorPrimitives.baseBlack),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "base-transparent-white", reference: "PregoColorPrimitives.baseTransparentWhite", value: PregoColorPrimitives.baseTransparentWhite),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "base-transparent-black", reference: "PregoColorPrimitives.baseTransparentBlack", value: PregoColorPrimitives.baseTransparentBlack),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray25", reference: "PregoColorPrimitives.gray25", value: PregoColorPrimitives.gray25),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray50", reference: "PregoColorPrimitives.gray50", value: PregoColorPrimitives.gray50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray100", reference: "PregoColorPrimitives.gray100", value: PregoColorPrimitives.gray100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray200", reference: "PregoColorPrimitives.gray200", value: PregoColorPrimitives.gray200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray300", reference: "PregoColorPrimitives.gray300", value: PregoColorPrimitives.gray300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray350", reference: "PregoColorPrimitives.gray350", value: PregoColorPrimitives.gray350),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray400", reference: "PregoColorPrimitives.gray400", value: PregoColorPrimitives.gray400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray425", reference: "PregoColorPrimitives.gray425", value: PregoColorPrimitives.gray425),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray450", reference: "PregoColorPrimitives.gray450", value: PregoColorPrimitives.gray450),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray525", reference: "PregoColorPrimitives.gray525", value: PregoColorPrimitives.gray525),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray500", reference: "PregoColorPrimitives.gray500", value: PregoColorPrimitives.gray500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray600", reference: "PregoColorPrimitives.gray600", value: PregoColorPrimitives.gray600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray700", reference: "PregoColorPrimitives.gray700", value: PregoColorPrimitives.gray700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray800", reference: "PregoColorPrimitives.gray800", value: PregoColorPrimitives.gray800),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray900", reference: "PregoColorPrimitives.gray900", value: PregoColorPrimitives.gray900),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "gray950", reference: "PregoColorPrimitives.gray950", value: PregoColorPrimitives.gray950),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white25", reference: "PregoColorPrimitives.alphaWhite25", value: PregoColorPrimitives.alphaWhite25),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white50", reference: "PregoColorPrimitives.alphaWhite50", value: PregoColorPrimitives.alphaWhite50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white100", reference: "PregoColorPrimitives.alphaWhite100", value: PregoColorPrimitives.alphaWhite100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white200", reference: "PregoColorPrimitives.alphaWhite200", value: PregoColorPrimitives.alphaWhite200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white300", reference: "PregoColorPrimitives.alphaWhite300", value: PregoColorPrimitives.alphaWhite300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white400", reference: "PregoColorPrimitives.alphaWhite400", value: PregoColorPrimitives.alphaWhite400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white500", reference: "PregoColorPrimitives.alphaWhite500", value: PregoColorPrimitives.alphaWhite500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white600", reference: "PregoColorPrimitives.alphaWhite600", value: PregoColorPrimitives.alphaWhite600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white700", reference: "PregoColorPrimitives.alphaWhite700", value: PregoColorPrimitives.alphaWhite700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white800", reference: "PregoColorPrimitives.alphaWhite800", value: PregoColorPrimitives.alphaWhite800),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white900", reference: "PregoColorPrimitives.alphaWhite900", value: PregoColorPrimitives.alphaWhite900),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-white950", reference: "PregoColorPrimitives.alphaWhite950", value: PregoColorPrimitives.alphaWhite950),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black25", reference: "PregoColorPrimitives.alphaBlack25", value: PregoColorPrimitives.alphaBlack25),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black50", reference: "PregoColorPrimitives.alphaBlack50", value: PregoColorPrimitives.alphaBlack50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black100", reference: "PregoColorPrimitives.alphaBlack100", value: PregoColorPrimitives.alphaBlack100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black200", reference: "PregoColorPrimitives.alphaBlack200", value: PregoColorPrimitives.alphaBlack200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black300", reference: "PregoColorPrimitives.alphaBlack300", value: PregoColorPrimitives.alphaBlack300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black400", reference: "PregoColorPrimitives.alphaBlack400", value: PregoColorPrimitives.alphaBlack400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black500", reference: "PregoColorPrimitives.alphaBlack500", value: PregoColorPrimitives.alphaBlack500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black600", reference: "PregoColorPrimitives.alphaBlack600", value: PregoColorPrimitives.alphaBlack600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black700", reference: "PregoColorPrimitives.alphaBlack700", value: PregoColorPrimitives.alphaBlack700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black800", reference: "PregoColorPrimitives.alphaBlack800", value: PregoColorPrimitives.alphaBlack800),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black900", reference: "PregoColorPrimitives.alphaBlack900", value: PregoColorPrimitives.alphaBlack900),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-black950", reference: "PregoColorPrimitives.alphaBlack950", value: PregoColorPrimitives.alphaBlack950),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray25", reference: "PregoColorPrimitives.alphaGray25", value: PregoColorPrimitives.alphaGray25),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray50", reference: "PregoColorPrimitives.alphaGray50", value: PregoColorPrimitives.alphaGray50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray100", reference: "PregoColorPrimitives.alphaGray100", value: PregoColorPrimitives.alphaGray100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray200", reference: "PregoColorPrimitives.alphaGray200", value: PregoColorPrimitives.alphaGray200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray300", reference: "PregoColorPrimitives.alphaGray300", value: PregoColorPrimitives.alphaGray300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray350", reference: "PregoColorPrimitives.alphaGray350", value: PregoColorPrimitives.alphaGray350),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray400", reference: "PregoColorPrimitives.alphaGray400", value: PregoColorPrimitives.alphaGray400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray500", reference: "PregoColorPrimitives.alphaGray500", value: PregoColorPrimitives.alphaGray500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray600", reference: "PregoColorPrimitives.alphaGray600", value: PregoColorPrimitives.alphaGray600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray700", reference: "PregoColorPrimitives.alphaGray700", value: PregoColorPrimitives.alphaGray700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray800", reference: "PregoColorPrimitives.alphaGray800", value: PregoColorPrimitives.alphaGray800),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray900", reference: "PregoColorPrimitives.alphaGray900", value: PregoColorPrimitives.alphaGray900),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "alpha-gray950", reference: "PregoColorPrimitives.alphaGray950", value: PregoColorPrimitives.alphaGray950),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue25", reference: "PregoColorPrimitives.blue25", value: PregoColorPrimitives.blue25),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue50", reference: "PregoColorPrimitives.blue50", value: PregoColorPrimitives.blue50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue100", reference: "PregoColorPrimitives.blue100", value: PregoColorPrimitives.blue100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue200", reference: "PregoColorPrimitives.blue200", value: PregoColorPrimitives.blue200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue300", reference: "PregoColorPrimitives.blue300", value: PregoColorPrimitives.blue300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue400", reference: "PregoColorPrimitives.blue400", value: PregoColorPrimitives.blue400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue500", reference: "PregoColorPrimitives.blue500", value: PregoColorPrimitives.blue500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue600", reference: "PregoColorPrimitives.blue600", value: PregoColorPrimitives.blue600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue700", reference: "PregoColorPrimitives.blue700", value: PregoColorPrimitives.blue700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue800", reference: "PregoColorPrimitives.blue800", value: PregoColorPrimitives.blue800),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue900", reference: "PregoColorPrimitives.blue900", value: PregoColorPrimitives.blue900),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "blue950", reference: "PregoColorPrimitives.blue950", value: PregoColorPrimitives.blue950),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error25", reference: "PregoColorPrimitives.error25", value: PregoColorPrimitives.error25),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error50", reference: "PregoColorPrimitives.error50", value: PregoColorPrimitives.error50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error100", reference: "PregoColorPrimitives.error100", value: PregoColorPrimitives.error100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error200", reference: "PregoColorPrimitives.error200", value: PregoColorPrimitives.error200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error300", reference: "PregoColorPrimitives.error300", value: PregoColorPrimitives.error300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error400", reference: "PregoColorPrimitives.error400", value: PregoColorPrimitives.error400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error500", reference: "PregoColorPrimitives.error500", value: PregoColorPrimitives.error500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error600", reference: "PregoColorPrimitives.error600", value: PregoColorPrimitives.error600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error700", reference: "PregoColorPrimitives.error700", value: PregoColorPrimitives.error700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error800", reference: "PregoColorPrimitives.error800", value: PregoColorPrimitives.error800),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error900", reference: "PregoColorPrimitives.error900", value: PregoColorPrimitives.error900),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "error950", reference: "PregoColorPrimitives.error950", value: PregoColorPrimitives.error950),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning25", reference: "PregoColorPrimitives.warning25", value: PregoColorPrimitives.warning25),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning50", reference: "PregoColorPrimitives.warning50", value: PregoColorPrimitives.warning50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning100", reference: "PregoColorPrimitives.warning100", value: PregoColorPrimitives.warning100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning200", reference: "PregoColorPrimitives.warning200", value: PregoColorPrimitives.warning200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning300", reference: "PregoColorPrimitives.warning300", value: PregoColorPrimitives.warning300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning400", reference: "PregoColorPrimitives.warning400", value: PregoColorPrimitives.warning400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning500", reference: "PregoColorPrimitives.warning500", value: PregoColorPrimitives.warning500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning600", reference: "PregoColorPrimitives.warning600", value: PregoColorPrimitives.warning600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning700", reference: "PregoColorPrimitives.warning700", value: PregoColorPrimitives.warning700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning800", reference: "PregoColorPrimitives.warning800", value: PregoColorPrimitives.warning800),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning900", reference: "PregoColorPrimitives.warning900", value: PregoColorPrimitives.warning900),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "warning950", reference: "PregoColorPrimitives.warning950", value: PregoColorPrimitives.warning950),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success25", reference: "PregoColorPrimitives.success25", value: PregoColorPrimitives.success25),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success50", reference: "PregoColorPrimitives.success50", value: PregoColorPrimitives.success50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success100", reference: "PregoColorPrimitives.success100", value: PregoColorPrimitives.success100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success200", reference: "PregoColorPrimitives.success200", value: PregoColorPrimitives.success200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success300", reference: "PregoColorPrimitives.success300", value: PregoColorPrimitives.success300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success400", reference: "PregoColorPrimitives.success400", value: PregoColorPrimitives.success400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success500", reference: "PregoColorPrimitives.success500", value: PregoColorPrimitives.success500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success600", reference: "PregoColorPrimitives.success600", value: PregoColorPrimitives.success600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success700", reference: "PregoColorPrimitives.success700", value: PregoColorPrimitives.success700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success800", reference: "PregoColorPrimitives.success800", value: PregoColorPrimitives.success800),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success900", reference: "PregoColorPrimitives.success900", value: PregoColorPrimitives.success900),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "success950", reference: "PregoColorPrimitives.success950", value: PregoColorPrimitives.success950),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple25", reference: "PregoColorPrimitives.purple25", value: PregoColorPrimitives.purple25),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple50", reference: "PregoColorPrimitives.purple50", value: PregoColorPrimitives.purple50),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple100", reference: "PregoColorPrimitives.purple100", value: PregoColorPrimitives.purple100),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple200", reference: "PregoColorPrimitives.purple200", value: PregoColorPrimitives.purple200),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple300", reference: "PregoColorPrimitives.purple300", value: PregoColorPrimitives.purple300),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple400", reference: "PregoColorPrimitives.purple400", value: PregoColorPrimitives.purple400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple500", reference: "PregoColorPrimitives.purple500", value: PregoColorPrimitives.purple500),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple600", reference: "PregoColorPrimitives.purple600", value: PregoColorPrimitives.purple600),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple700", reference: "PregoColorPrimitives.purple700", value: PregoColorPrimitives.purple700),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple800", reference: "PregoColorPrimitives.purple800", value: PregoColorPrimitives.purple800),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple900", reference: "PregoColorPrimitives.purple900", value: PregoColorPrimitives.purple900),
  PregoInspectionToken(kind: PregoInspectionTokenKind.primitiveColor, name: "purple950", reference: "PregoColorPrimitives.purple950", value: PregoColorPrimitives.purple950),
];

List<PregoInspectionToken<TextStyle>> buildPregoInspectionTypographyTokens(PregoTextTheme theme) => [
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display2xl / light", reference: "context.prego.textTheme.display2xl.light", value: theme.display2xl.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display2xl / regular", reference: "context.prego.textTheme.display2xl.regular", value: theme.display2xl.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display2xl / medium", reference: "context.prego.textTheme.display2xl.medium", value: theme.display2xl.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display2xl / bold", reference: "context.prego.textTheme.display2xl.bold", value: theme.display2xl.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display2xl / black", reference: "context.prego.textTheme.display2xl.black", value: theme.display2xl.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xl / light", reference: "context.prego.textTheme.displayXl.light", value: theme.displayXl.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xl / regular", reference: "context.prego.textTheme.displayXl.regular", value: theme.displayXl.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xl / medium", reference: "context.prego.textTheme.displayXl.medium", value: theme.displayXl.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xl / bold", reference: "context.prego.textTheme.displayXl.bold", value: theme.displayXl.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xl / black", reference: "context.prego.textTheme.displayXl.black", value: theme.displayXl.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-lg / light", reference: "context.prego.textTheme.displayLg.light", value: theme.displayLg.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-lg / regular", reference: "context.prego.textTheme.displayLg.regular", value: theme.displayLg.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-lg / medium", reference: "context.prego.textTheme.displayLg.medium", value: theme.displayLg.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-lg / bold", reference: "context.prego.textTheme.displayLg.bold", value: theme.displayLg.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-lg / black", reference: "context.prego.textTheme.displayLg.black", value: theme.displayLg.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-md / light", reference: "context.prego.textTheme.displayMd.light", value: theme.displayMd.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-md / regular", reference: "context.prego.textTheme.displayMd.regular", value: theme.displayMd.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-md / medium", reference: "context.prego.textTheme.displayMd.medium", value: theme.displayMd.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-md / bold", reference: "context.prego.textTheme.displayMd.bold", value: theme.displayMd.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-md / black", reference: "context.prego.textTheme.displayMd.black", value: theme.displayMd.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-sm / light", reference: "context.prego.textTheme.displaySm.light", value: theme.displaySm.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-sm / regular", reference: "context.prego.textTheme.displaySm.regular", value: theme.displaySm.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-sm / medium", reference: "context.prego.textTheme.displaySm.medium", value: theme.displaySm.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-sm / bold", reference: "context.prego.textTheme.displaySm.bold", value: theme.displaySm.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-sm / black", reference: "context.prego.textTheme.displaySm.black", value: theme.displaySm.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xs / light", reference: "context.prego.textTheme.displayXs.light", value: theme.displayXs.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xs / regular", reference: "context.prego.textTheme.displayXs.regular", value: theme.displayXs.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xs / medium", reference: "context.prego.textTheme.displayXs.medium", value: theme.displayXs.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xs / bold", reference: "context.prego.textTheme.displayXs.bold", value: theme.displayXs.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "display-xs / black", reference: "context.prego.textTheme.displayXs.black", value: theme.displayXs.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xl / light", reference: "context.prego.textTheme.textXl.light", value: theme.textXl.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xl / regular", reference: "context.prego.textTheme.textXl.regular", value: theme.textXl.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xl / medium", reference: "context.prego.textTheme.textXl.medium", value: theme.textXl.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xl / bold", reference: "context.prego.textTheme.textXl.bold", value: theme.textXl.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xl / black", reference: "context.prego.textTheme.textXl.black", value: theme.textXl.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-lg / light", reference: "context.prego.textTheme.textLg.light", value: theme.textLg.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-lg / regular", reference: "context.prego.textTheme.textLg.regular", value: theme.textLg.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-lg / medium", reference: "context.prego.textTheme.textLg.medium", value: theme.textLg.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-lg / bold", reference: "context.prego.textTheme.textLg.bold", value: theme.textLg.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-lg / black", reference: "context.prego.textTheme.textLg.black", value: theme.textLg.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-md / light", reference: "context.prego.textTheme.textMd.light", value: theme.textMd.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-md / regular", reference: "context.prego.textTheme.textMd.regular", value: theme.textMd.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-md / medium", reference: "context.prego.textTheme.textMd.medium", value: theme.textMd.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-md / bold", reference: "context.prego.textTheme.textMd.bold", value: theme.textMd.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-md / black", reference: "context.prego.textTheme.textMd.black", value: theme.textMd.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-sm / light", reference: "context.prego.textTheme.textSm.light", value: theme.textSm.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-sm / regular", reference: "context.prego.textTheme.textSm.regular", value: theme.textSm.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-sm / medium", reference: "context.prego.textTheme.textSm.medium", value: theme.textSm.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-sm / bold", reference: "context.prego.textTheme.textSm.bold", value: theme.textSm.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-sm / black", reference: "context.prego.textTheme.textSm.black", value: theme.textSm.black),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xs / light", reference: "context.prego.textTheme.textXs.light", value: theme.textXs.light),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xs / regular", reference: "context.prego.textTheme.textXs.regular", value: theme.textXs.regular),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xs / medium", reference: "context.prego.textTheme.textXs.medium", value: theme.textXs.medium),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xs / bold", reference: "context.prego.textTheme.textXs.bold", value: theme.textXs.bold),
  PregoInspectionToken(kind: PregoInspectionTokenKind.typography, name: "text-xs / black", reference: "context.prego.textTheme.textXs.black", value: theme.textXs.black),
];

const pregoInspectionDimensionTokens = <PregoInspectionToken<double>>[
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "none", reference: "context.prego.spacing.none", value: PregoSpacing.none),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "xxs", reference: "context.prego.spacing.xxs", value: PregoSpacing.xxs),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "xs", reference: "context.prego.spacing.xs", value: PregoSpacing.xs),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "sm", reference: "context.prego.spacing.sm", value: PregoSpacing.sm),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "md", reference: "context.prego.spacing.md", value: PregoSpacing.md),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "lg", reference: "context.prego.spacing.lg", value: PregoSpacing.lg),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "xl", reference: "context.prego.spacing.xl", value: PregoSpacing.xl),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x2l", reference: "context.prego.spacing.x2l", value: PregoSpacing.x2l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x3l", reference: "context.prego.spacing.x3l", value: PregoSpacing.x3l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x4l", reference: "context.prego.spacing.x4l", value: PregoSpacing.x4l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x5l", reference: "context.prego.spacing.x5l", value: PregoSpacing.x5l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x6l", reference: "context.prego.spacing.x6l", value: PregoSpacing.x6l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x7l", reference: "context.prego.spacing.x7l", value: PregoSpacing.x7l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x8l", reference: "context.prego.spacing.x8l", value: PregoSpacing.x8l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x9l", reference: "context.prego.spacing.x9l", value: PregoSpacing.x9l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x10l", reference: "context.prego.spacing.x10l", value: PregoSpacing.x10l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "x11l", reference: "context.prego.spacing.x11l", value: PregoSpacing.x11l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "container-padding-mobile", reference: "context.prego.spacing.containerPaddingMobile", value: PregoSpacing.containerPaddingMobile),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "container-padding-desktop", reference: "context.prego.spacing.containerPaddingDesktop", value: PregoSpacing.containerPaddingDesktop),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacing, name: "container-max-width-desktop", reference: "context.prego.spacing.containerMaxWidthDesktop", value: PregoSpacing.containerMaxWidthDesktop),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing0", reference: "PregoSpacingPrimitives.spacing0", value: PregoSpacingPrimitives.spacing0),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing0_5", reference: "PregoSpacingPrimitives.spacing0_5", value: PregoSpacingPrimitives.spacing0_5),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing1", reference: "PregoSpacingPrimitives.spacing1", value: PregoSpacingPrimitives.spacing1),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing1_5", reference: "PregoSpacingPrimitives.spacing1_5", value: PregoSpacingPrimitives.spacing1_5),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing2", reference: "PregoSpacingPrimitives.spacing2", value: PregoSpacingPrimitives.spacing2),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing3", reference: "PregoSpacingPrimitives.spacing3", value: PregoSpacingPrimitives.spacing3),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing4", reference: "PregoSpacingPrimitives.spacing4", value: PregoSpacingPrimitives.spacing4),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing5", reference: "PregoSpacingPrimitives.spacing5", value: PregoSpacingPrimitives.spacing5),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing6", reference: "PregoSpacingPrimitives.spacing6", value: PregoSpacingPrimitives.spacing6),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing8", reference: "PregoSpacingPrimitives.spacing8", value: PregoSpacingPrimitives.spacing8),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing10", reference: "PregoSpacingPrimitives.spacing10", value: PregoSpacingPrimitives.spacing10),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing12", reference: "PregoSpacingPrimitives.spacing12", value: PregoSpacingPrimitives.spacing12),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing16", reference: "PregoSpacingPrimitives.spacing16", value: PregoSpacingPrimitives.spacing16),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing20", reference: "PregoSpacingPrimitives.spacing20", value: PregoSpacingPrimitives.spacing20),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing24", reference: "PregoSpacingPrimitives.spacing24", value: PregoSpacingPrimitives.spacing24),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing32", reference: "PregoSpacingPrimitives.spacing32", value: PregoSpacingPrimitives.spacing32),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing40", reference: "PregoSpacingPrimitives.spacing40", value: PregoSpacingPrimitives.spacing40),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing48", reference: "PregoSpacingPrimitives.spacing48", value: PregoSpacingPrimitives.spacing48),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing56", reference: "PregoSpacingPrimitives.spacing56", value: PregoSpacingPrimitives.spacing56),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing64", reference: "PregoSpacingPrimitives.spacing64", value: PregoSpacingPrimitives.spacing64),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing80", reference: "PregoSpacingPrimitives.spacing80", value: PregoSpacingPrimitives.spacing80),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing96", reference: "PregoSpacingPrimitives.spacing96", value: PregoSpacingPrimitives.spacing96),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing120", reference: "PregoSpacingPrimitives.spacing120", value: PregoSpacingPrimitives.spacing120),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing140", reference: "PregoSpacingPrimitives.spacing140", value: PregoSpacingPrimitives.spacing140),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing160", reference: "PregoSpacingPrimitives.spacing160", value: PregoSpacingPrimitives.spacing160),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing180", reference: "PregoSpacingPrimitives.spacing180", value: PregoSpacingPrimitives.spacing180),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing192", reference: "PregoSpacingPrimitives.spacing192", value: PregoSpacingPrimitives.spacing192),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing256", reference: "PregoSpacingPrimitives.spacing256", value: PregoSpacingPrimitives.spacing256),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing320", reference: "PregoSpacingPrimitives.spacing320", value: PregoSpacingPrimitives.spacing320),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing360", reference: "PregoSpacingPrimitives.spacing360", value: PregoSpacingPrimitives.spacing360),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing400", reference: "PregoSpacingPrimitives.spacing400", value: PregoSpacingPrimitives.spacing400),
  PregoInspectionToken(kind: PregoInspectionTokenKind.spacingPrimitive, name: "spacing480", reference: "PregoSpacingPrimitives.spacing480", value: PregoSpacingPrimitives.spacing480),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "none", reference: "context.prego.radius.none", value: PregoRadius.none),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "xxs", reference: "context.prego.radius.xxs", value: PregoRadius.xxs),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "xs", reference: "context.prego.radius.xs", value: PregoRadius.xs),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "sm", reference: "context.prego.radius.sm", value: PregoRadius.sm),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "md", reference: "context.prego.radius.md", value: PregoRadius.md),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "lg", reference: "context.prego.radius.lg", value: PregoRadius.lg),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "xl", reference: "context.prego.radius.xl", value: PregoRadius.xl),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "x2l", reference: "context.prego.radius.x2l", value: PregoRadius.x2l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "x3l", reference: "context.prego.radius.x3l", value: PregoRadius.x3l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "x4l", reference: "context.prego.radius.x4l", value: PregoRadius.x4l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "x5l", reference: "context.prego.radius.x5l", value: PregoRadius.x5l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "x6l", reference: "context.prego.radius.x6l", value: PregoRadius.x6l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "x8l", reference: "context.prego.radius.x8l", value: PregoRadius.x8l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.radius, name: "full", reference: "context.prego.radius.full", value: PregoRadius.full),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "xxs", reference: "context.prego.widths.xxs", value: PregoWidths.xxs),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "xs", reference: "context.prego.widths.xs", value: PregoWidths.xs),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "sm", reference: "context.prego.widths.sm", value: PregoWidths.sm),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "md", reference: "context.prego.widths.md", value: PregoWidths.md),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "lg", reference: "context.prego.widths.lg", value: PregoWidths.lg),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "xl", reference: "context.prego.widths.xl", value: PregoWidths.xl),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "x2l", reference: "context.prego.widths.x2l", value: PregoWidths.x2l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "x3l", reference: "context.prego.widths.x3l", value: PregoWidths.x3l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "x4l", reference: "context.prego.widths.x4l", value: PregoWidths.x4l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "x5l", reference: "context.prego.widths.x5l", value: PregoWidths.x5l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "x6l", reference: "context.prego.widths.x6l", value: PregoWidths.x6l),
  PregoInspectionToken(kind: PregoInspectionTokenKind.width, name: "paragraph-max-width", reference: "context.prego.widths.paragraphMaxWidth", value: PregoWidths.paragraphMaxWidth),
];

