// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHPMJoI7bDGaLBQy9svR3ZAxrZ5uyTmUk',
    appId: '1:1068630921159:web:7e1ca402c07abd839713e2',
    messagingSenderId: '1068630921159',
    projectId: 'sesori-ai',
    authDomain: 'sesori-ai.firebaseapp.com',
    storageBucket: 'sesori-ai.firebasestorage.app',
    measurementId: 'G-983V8YK5ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74UArBB7wMT586r2LC1tYuh9F0SigovM',
    appId: '1:1068630921159:android:741baef698c95d6f9713e2',
    messagingSenderId: '1068630921159',
    projectId: 'sesori-ai',
    storageBucket: 'sesori-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo3Xr3367r8QWh7A_swXdFMO0FMoS9eAE',
    appId: '1:1068630921159:ios:14f05dc19d66cba89713e2',
    messagingSenderId: '1068630921159',
    projectId: 'sesori-ai',
    storageBucket: 'sesori-ai.firebasestorage.app',
    iosBundleId: 'com.sesori.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo3Xr3367r8QWh7A_swXdFMO0FMoS9eAE',
    appId: '1:1068630921159:ios:14f05dc19d66cba89713e2',
    messagingSenderId: '1068630921159',
    projectId: 'sesori-ai',
    storageBucket: 'sesori-ai.firebasestorage.app',
    iosBundleId: 'com.sesori.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHPMJoI7bDGaLBQy9svR3ZAxrZ5uyTmUk',
    appId: '1:1068630921159:web:66825b03e205bc0d9713e2',
    messagingSenderId: '1068630921159',
    projectId: 'sesori-ai',
    authDomain: 'sesori-ai.firebaseapp.com',
    storageBucket: 'sesori-ai.firebasestorage.app',
    measurementId: 'G-4XM8JKECNM',
  );
}
