import "package:flutter/material.dart";

import "sesori_theme_tokens.dart";

final lightColorScheme =
    const ColorScheme(
      brightness: Brightness.light,
      primary: SesoriThemeTokens.lightPrimary,
      onPrimary: Colors.white,
      primaryContainer: Color(0xFFE3EBFF),
      onPrimaryContainer: Color(0xFF06152D),
      secondary: SesoriThemeTokens.lightAccent,
      onSecondary: Colors.white,
      secondaryContainer: Color(0xFFDCEBFF),
      onSecondaryContainer: Color(0xFF072142),
      tertiary: SesoriThemeTokens.lightSuccess,
      onTertiary: Colors.white,
      tertiaryContainer: Color(0xFFB8F0DE),
      onTertiaryContainer: Color(0xFF05261D),
      error: SesoriThemeTokens.lightDanger,
      onError: Colors.white,
      errorContainer: Color(0xFFFFE0DE),
      onErrorContainer: Color(0xFF3B0904),
      surface: SesoriThemeTokens.lightSurface,
      onSurface: Color(0xFF11141B),
      onSurfaceVariant: Color(0xFF566173),
      outline: Color(0xFF7B8697),
      outlineVariant: SesoriThemeTokens.lightBorder,
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFF171D29),
      onInverseSurface: Color(0xFFF4F7FC),
      inversePrimary: Color(0xFFB7D2FF),
      surfaceTint: SesoriThemeTokens.lightAccent,
    ).copyWith(
      surfaceContainerLowest: Colors.white,
      surfaceContainerLow: const Color(0xFFF8FAFD),
      surfaceContainer: SesoriThemeTokens.lightSurfaceMuted,
      surfaceContainerHigh: const Color(0xFFE8ECF3),
      surfaceContainerHighest: const Color(0xFFDDE3EE),
    );

final darkColorScheme =
    const ColorScheme(
      brightness: Brightness.dark,
      primary: SesoriThemeTokens.darkPrimary,
      onPrimary: Color(0xFF001E4E),
      primaryContainer: Color(0xFF12366D),
      onPrimaryContainer: Color(0xFFDCE9FF),
      secondary: SesoriThemeTokens.darkAccent,
      onSecondary: Color(0xFF112446),
      secondaryContainer: Color(0xFF1D3560),
      onSecondaryContainer: Color(0xFFDCE6FF),
      tertiary: SesoriThemeTokens.darkSuccess,
      onTertiary: Color(0xFF003829),
      tertiaryContainer: Color(0xFF0A5140),
      onTertiaryContainer: Color(0xFFC8FFEC),
      error: SesoriThemeTokens.darkDanger,
      onError: Color(0xFF5A0B0C),
      errorContainer: Color(0xFF7A1A1D),
      onErrorContainer: Color(0xFFFFDAD8),
      surface: SesoriThemeTokens.darkSurface,
      onSurface: Color(0xFFF2F5FA),
      onSurfaceVariant: Color(0xFFB7C1D3),
      outline: Color(0xFF8893A8),
      outlineVariant: SesoriThemeTokens.darkBorder,
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: Color(0xFFF2F5FA),
      onInverseSurface: Color(0xFF171D29),
      inversePrimary: Color(0xFF174FA8),
      surfaceTint: SesoriThemeTokens.darkPrimary,
    ).copyWith(
      surfaceContainerLowest: const Color(0xFF06080F),
      surfaceContainerLow: const Color(0xFF0D111B),
      surfaceContainer: SesoriThemeTokens.darkSurface,
      surfaceContainerHigh: SesoriThemeTokens.darkSurfaceMuted,
      surfaceContainerHighest: const Color(0xFF1D2433),
    );
