targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_manager: false
      freezed:
        options:
          format: false
          map: false
          when: false
